[Feat] #7- 추천뷰레이아웃구현
team-peekabook/Peekabook-iOS pull request #12
Opened 2023-01-03 18:54 UTC by 6uohul

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#7

👷 **작업한 내용**

- 추천받은 책, 추천한 책을 보여주는 추천 뷰 레이아웃을 구현

## 🚨 참고 사항

- 아직 셀 내부의 친구 책장보러가기 버튼은 동작하지 않아요
- Cell의 폴더링을 어떻게 해야하는지 모르겠어요
## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 13 Pro - 2023-01-04 at 03 40 06](https://user-images.githubusercontent.com/83493636/210422116-452f7200-c9e8-4381-b770-e7e13b610719.gif)|

## 📟 관련 이슈
- Resolved: #7

2023-01-04 01:39 UTC, devxsby requested changes
font 넣어준걸로 바꿔주세용~~
전체적으로 너무 잘하셨고
제가 코멘트 남긴거 다른 파일에도 해당사항 있는지 변경할 만한 것 있는지 한 번 더 확인해주세요~~!
고생하셨어요 !! 🤎

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +    static let identifier = "RecommendTableViewCell"
p3
getClassName 쓰면 여기 14번째 줄은 삭제할 수 있어요
사용법은 밑에서 알려드릴게여

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +class RecommendTableViewCell: UITableViewCell {
p3
해당 클래스가 상속받지 않는다면 `final` 키워드를 붙여주세요
final 키워드에 대해선 다음에 상세히 공부해보면 좋을것같아요!
https://tdcian.tistory.com/303

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        $0.distribution = .fill
question
두 개의 코드는 어떤게 다를까요?

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        $0.backgroundColor = .peekaWhite
p4
각 컬러를 지정하는 코드에 컨벤션이 안맞는 것 같아요.
통일성을 주면 더 좋겠습니다~

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +    var menuName: [String] = ["추천받은 책", "추천한 책"]
p3
제가 바뀌지 않는 string들만 따로 관리하도록 StringLiteral 만들어놓았으니 거기로 빼서 작업하면 좋을거같아요
탭바에서 title 넣은거로 한 번 확인해주세요~

```swift
    struct 해당뷰 {
        static let 추천받은책 = "추천받은책"
        static let 추천한책 = "추천한책"
        . . .

```

그리고 개인적으로 menu라는게 뭔가 네이밍이 이상한것같아요. 
어떤 네이밍이 좋을지 한 번 더 고민해보시면 좋겠어요 ~~!

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +
p4.
셀 init 위에 `// MARK: - Initialization` 주석을 달아놓으면 조금 더 찾기 쉬울 것 같아요

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        addSubview()
p3.
지금도 잘 해주셨지만 !! 우리가 VC에서는 셀의 UI를 지정하는 코드와 레이아웃잡는 코드의 네이밍을 각각 `setUI`, `setLayout`으로 해놓았으니 컨벤션을 지키는 것이 좋아보입니다~~

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        self.backgroundColor = .peekaBeige
p3
이 코드는 레이아웃 잡는 코드가 아닌 것 같아요
위로 올려주세용!

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        }
p5.
요기부터 밑부분 한 줄씩 띄워주면 어떨까요?
```suggestion
        bookHeaderView.snp.makeConstraints { make in
             make.top.leading.trailing.equalToSuperview()
             make.height.equalTo(30)
         }
         
         bookNameLabel.snp.makeConstraints { make in
             make.centerY.equalToSuperview()
             make.leading.equalTo(15)
         }
```

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +    }
p3.
다른 파일에서 사용하지 않는 함수는 `private` 키워드를 붙여주는 것이 좋아보여요.
https://joycestudios.tistory.com/15

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +    }
p5.
네이밍이 약간 어색한 것 같아요. 이 함수에서 하는 일을 함수명에 작성해주면 어떨까요??

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +    // Menu Tab
p5.
이 주석은 꼭 필요한 걸까요?? 필요하지 않다면 지우는 것도 좋아보입니다~~!

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +    }
p3
위에서 말씀드린 `private` 접근제한자가 쓸 수 있는 곳에 웬만하면 다 붙여주세요~~

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +
p4.
아랫 부분은 view life cycle에 관련된 코드가 아니니까 `function`같은 마크 주석으로 분리시켜주시면 좋을 것 같아용

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +            make.top.leading.trailing.equalTo(view.safeAreaLayoutGuide)
p3.
줄바꿈 컨벤션 지켜주세효

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +        return dataViewControllers[previousIndex]
👍🏻👍🏻

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
> +    ]
p3.
위에서 언급한 것처럼 final, private 키워드 사악 검토 부탁드려요
그리고 한 라인이 너무 기니까 파라미터 별로 쪼개면 좀 더 보기 좋아보일것같아용~~
```swift
     var recommendedDummy: [RecommendModel] = [
         RecommendModel(image: ImageLiterals.Sample.book1,
                        bookName: "아무튼, 여름"
                        writer: "김신회",
                        recommendedPersonImage: ImageLiterals.Sample.profile3,
                        recommendedPerson: "김인영",
                        memo: "‘추천사요약’ 을 쓸 건데 나는 이 책이 상당한 지식을 얻을 수 있는 기회를 제공한다고 생각합니다. 당신에게 추천해요!"),
         RecommendModel(image: ImageLiterals.Sample.book1,
                        bookName: "아무튼, 여름",
                        writer: "김신회",
                        recommendedPersonImage: ImageLiterals.Sample.profile2,
                        recommendedPerson: "윤수빈",
                        memo: "‘추천사요약’ 을 쓸 건데 나는 이 책이 상당한 지식을 얻을 수 있는 기회를 제공한다고 생각합니다. 당신에게 추천해요!"),
...

```

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
> +        $0.dataSource = self
p5
저는 setDelegate 메서드 따로 만들어서 관리해주는 편!
이건 본인 스타일에 따라 참고만 해도 좋습니다~~

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
> +        RecommendModel(image: ImageLiterals.Sample.book4, bookName: "눈보라 체이스", writer: "양윤옥", recommendedPersonImage: ImageLiterals.Sample.profile3, recommendedPerson: "강희선배", memo: "‘추천사요약’ 을 쓸 건데 나
p3
여기도 마찬가지로 분리할 수 있겠네용

2023-01-04 01:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/TabMenuCollectionViewCell.swift
> +        }
question
변수 오버라이딩 하신 이유가 있으신가요??

2023-01-04 01:43 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: TabMenuCollectionViewCell.identifier, for: indexPath) as? TabMenuCollectionViewCell else { return UICollectionViewCell
```suggestion
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: TabMenuCollectionViewCell.className, for: indexPath) as? TabMenuCollectionViewCell else { return UICollectionViewCell() }
```

2023-01-04 06:32 UTC, duyeong-ko reviewed
우왕 인영앙 넘 멋지다... 🔥 고생해써

2023-01-04 16:04 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +class RecommendTableViewCell: UITableViewCell {
와!! 감사합니다 공부해볼게용

2023-01-04 16:07 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        $0.distribution = .fill
alignment는 수직기준, distribution은 수평기준으로 알고있는데 맞을까용..??

2023-01-04 16:07 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendTableViewCell.swift
> +        $0.backgroundColor = .peekaWhite
헉 그러네요 바로 수정하겠습니다!!

2023-01-04 16:26 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +    var menuName: [String] = ["추천받은 책", "추천한 책"]
안그래도 좀 찝찝했던 부분이었는데 시원하게 긁어주셨어요..
RecommendTypes 어떠신가요..

2023-01-04 16:27 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
> +    ]
넹!!!

2023-01-04 16:33 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendingVC.swift
> +        RecommendModel(image: ImageLiterals.Sample.book4, bookName: "눈보라 체이스", writer: "양윤옥", recommendedPersonImage: ImageLiterals.Sample.profile3, recommendedPerson: "강희선배", memo: "‘추천사요약’ 을 쓸 건데 나
넵~!! 바로 반영하겠슴돵

2023-01-04 16:51 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/TabMenuCollectionViewCell.swift
> +        }
isSelected만 있어도 될것같아요 ㅎ.. 
수정하겠습니돠

2023-01-04 16:57 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: TabMenuCollectionViewCell.identifier, for: indexPath) as? TabMenuCollectionViewCell else { return UICollectionViewCell
오 이제 진짜 잘 활용할게요 충성 🫡

2023-01-05 01:13 UTC, devxsby approved these changes

2023-01-05 01:13 UTC, merged