[Fix] #153 - 책 등록/수정/추천뷰 리팩토링
team-peekabook/Peekabook-iOS pull request #154
Opened 2023-02-03 09:31 UTC by duyeong-ko

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#153

👷 **작업한 내용**

- 파일명 및 경로정리
- 한마디, 메모 안쓰고 넘어갔을 때 엠티뷰 수정
- 책이름/작가이름 2줄넘으면 … 처리, 작가이름 ^ 쉼표로 수정
- 책 추천뷰 상단 네비바 위로 날라가는거 해결
- 기타등등..

## 🚨 참고 사항

- 일단 돼야하는데 안되는 것들 수정했어요 코드 깔끔하게 정리하는 것은 새로 이슈파서 할게용

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|:--:|:--:|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/101977975/216555963-febf1fe9-f2c2-4c84-ac9a-7000bbc78e53.png" width ="250">|<img src = "https://user-images.githubusercontent.com/101977975/216556236-61250fd7-c368-446d-8c43-539abb62857c.png" width ="250">|<img src = "https://user-images.githubusercontent.com/101977975/216556367-43a80499-44fc-4380-8a13-9c0b5a88ef11.png" width ="250">|<img src = "https://user-images.githubusercontent.com/101977975/216557096-9811e0d0-8a19-4871-80e4-33774e6a89ea.png" width ="250">|<img src = "https://user-images.githubusercontent.com/101977975/216557189-216de4b7-bf2c-4f61-8820-238c42881c08.png" width ="250">|

## 📟 관련 이슈
- Resolved: #153

2023-02-05 06:32 UTC, devxsby requested changes
고생했어요. 🫶🏻
카톡으루 말한거만 한 번 더 체크해주쎄용 ~

2023-02-05 06:32 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Proposal/VC/ProposalVC.swift
> +        print(position)
p3.
요긴 지워주세용~

2023-02-06 07:25 UTC, devxsby approved these changes

2023-02-06 07:25 UTC, devxsby commented on Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
> +            || (commentTextView.text.isEmpty == true) {
p3.
요기 그냥 `commentTextView.text.isEmpty` 로 해도 되지않나용...!??

2023-02-06 07:45 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/BookDetail/VC/BookDetailVC.swift
> +            || (commentTextView.text.isEmpty == true) {
요거 아예 클릭도 안한채로 (placeholder 있는채로) 넘어가면 textView.text == I18N.BookDetail.memoHint 이런식으로 저장돼서 isEmty가 아니어서,, isEmpty만 하면 안되더라구용,,

2023-02-06 07:46 UTC, merged