[Refactor] #159 컴포넌트화 등 리팩토링
team-peekabook/Peekabook-iOS pull request #160
Opened 2023-02-24 08:32 UTC by duyeong-ko

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#159

👷 **작업한 내용**

- 키보드 firstResponder, return타입 수정
- 📍책등록뷰, 📍책상세뷰, 📍책수정뷰 - 텍스트뷰 컴포넌트화
- 책수정 시 텍스트와 placeholder에 따른 분기처리 추가/수정
- 📍책검색뷰, 📍사용자검색뷰 - 검색뷰 컴포넌트화
- make in -> $0 변경
- 기타 코드 수정

## 🚨 참고 사항

텍스트뷰(아래 스크린샷 첫번째) 컴포넌트화할때 textviewDelegate는 같이 재사용했는데
키보드 관련 코드(키보드 나타날 때 뷰 조금 올라가는 것)는 코드 중 containerView의 contentInset 등을 사용하는,, 코드가 있어서
컴포넌트 뷰에는 containerView가 없기때문에 (사용할 뷰 안의 containerView 안에 컴포넌트가 들어있어서)
키보드 코드는 재사용하지 못했습니다,,

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/101977975/221129329-3633102f-4fe1-487d-b2eb-6707a9f7e583.png" width ="250">|
|GIF|<img src = "https://user-images.githubusercontent.com/101977975/221129391-e07e1d35-371a-4c91-a250-19ff8d55d51c.png" width ="250">|

## 📟 관련 이슈
- Resolved: #159

2023-02-25 06:22 UTC, devxsby requested changes
두두 고생했어 🤍
코멘트 단 것만 확인해줘~~!!
구리고 위에 적어놓은 부분은 나중에 커스텀 하는 방식을 더 다양하게 익히게 되면 할 수 있을거야!!
일단 너무 잘했어~~!! 🚀

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +class CommentView: UIView {
p3;
상속받지 않는다면 `final class`로 바꿀 수 있겠네용
추가로 제 생각에 CommentView라는 파일명은 모호한 면이 있는 것 같아요..
파일명이 길어져도 좋으니 이름만 보고 어떠한 역할을 맡는 뷰인지 알 수 있도록 변경하는 것이 좋겠네용.
예를 들어 이 커스텀 뷰는 텍스트 뷰를 감싸놓은 뷰니까 파일명에 `CustomTextView` 라고 해서 텍스트 뷰라고 알수 있또록 하면 조금 더 이해가 쉽지 않을까 싶습니다~~

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +
p3;
컴포넌트 요소들에 `internal`로 접근제한이 되어있는데 `private`으로 바꾸고 은닉화해주면 더 좋겠네용.

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +    }
p2;
`addObserver`가 없는걸봐선 이 코드는 안쓰는거같은데 맞나용?
안쓴다면 지워주세요~

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +    }
p3;
`comment`라는 네이밍이 공통적으로 들어갔는데 사실 이 커스텀 뷰는 comment(한마디), memo(메모), 책 추천 등 여러가지에서 쓰일 수 있는 컴포넌트이죠.
따라서 `comment`라고 적은 것들은 모두 빼줘도 될 것 같아요~~
이 뷰에서 어떤 역할을 맡고 있는지에 대해 네이밍을 생각해보고 지정해주면 더 좋겠습니당 👍🏻

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +            (textView.text == I18N.BookDetail.emptyMemo) {
question;
사용자가 한마디를 힌트랑 똑같이 `한 마디를 작성해주세요.` 와 같이 적은 경우에는 어떻게 되는걸까요??
여기 서버 연결부분은 제대로 들어가나용?

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +class SearchView: UIView {
p3;
위에 코멘트 남긴 것처럼 `final class`로 지정해주세요~~
이름도 통일성 있게 `CustomSearchView`로 변경하는 것도 좋아보여요

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    let searchContainerView = UIView()
p2;
접근 제한자 싹 검토해주세용

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    }
p3;
이 친구는 lazy var로 하신 특별한 이유가 있으실까용~~?

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    // MARK: - Initialization
주석 야무지게 잘 다셨네용 ⭐️

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    }
p4;
`UIComponets` 선언 해준 부분에서 배경색 지정한거랑 이 `setUI` 메서드에서 하는 역할이 겹치고 모호한 것 같아요.
본인만의 기준을 명확히 하고 통일성을 갖추면 더욱 좋을 것 같습니다~~

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +        addSubviews(searchContainerView)
p4;
`searchContainerView`한 개만 addSubview할 때는 컨테이너 뷰만 1개 추가하고, 나머지 뷰들은 `ContentView`에 실수로 추가되지 않도록 `addSubview` 메서드로만 적고 단일 뷰만 추가하는 방식을 써볼 수 있겠네요~

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +            $0.leading.trailing.equalToSuperview()
p2;
축약인자 잘 바꿔주셨습니다~~ 굿 🫶🏻
그런데 지금 `equalToSuperview` 하는 부분이 겹치는데 따로 두 줄로 지정해주셨네용~
한 줄로 합칠 수 있는 데는 합칩시돠

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
> +        getUserAPI(nickname: userSearchView.searchTextField.text!)
p3;
강제 언래핑 안하고 보내는게 안전하게 바인딩하는게 더 좋을거같아용

2023-02-25 06:22 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
> +    }
p4;
지금 여기 111 line에서 하는 행위와 `setReusableView`이라는 메서드 명이 잘 매칭이 안됩니다~~!

2023-02-25 07:38 UTC, 6uohul approved these changes
두영씨 컴포넌트화 너무 잘하셨네요..!! 저도 얼른 작업하겠습니다!
너무 수고하셨어용

2023-02-25 07:38 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/MemoView.swift
> +
크으 .. 컴포넌트화 배우고갑니다

2023-02-25 07:38 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +
👍🏻👍🏻👍🏻

2023-02-27 06:51 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +
private으로 바꾸면 다른 파일에서 접근하지 못한다고 뜨는데 은닉화할 수 있나용??

2023-02-27 06:52 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +    }
오오 감사합니다 🙏

2023-02-27 07:15 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    let searchContainerView = UIView()
여기도 다른 파일에서 접근해야하는 컴포넌트 요소들이라 private 붙이지 않았었어용,,!

2023-02-27 07:46 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    }
다른 vc에서 버튼 이벤트 추가하는 addTarget을 해주었기때문에 lazy var로 했습니당!!

2023-02-27 09:17 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CommentView.swift
> +
프로퍼티를 직접 노출하지말고 메서드를 만어서 그걸 개방시켜봐요

2023-02-27 09:18 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    let searchContainerView = UIView()
위에 남긴거랑 같아용
밖에서 접근해서 바꾸는 코드를 메서드(함수)로 만들어보세용

2023-02-27 09:18 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/SearchView.swift
> +    }
상태가 다 다른가보군요 일단 오케잉

2023-03-04 07:34 UTC, devxsby approved these changes

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
> +    private(set) var NaverSearchData: NaverSearchResponse?
p1;
변수는 lower camel case 사용해주세요~~

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
> +    func getNaverSearchData(d_titl: String, d_isbn: String, display: Int, completion: @escaping ([Item]?) -> Void) {
p2;
여기 dto 이름 Item 말고 다른거로 바꿔야 직관적일거같아요
수정 부탁드릴게용~!

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
> +                    completion(items)
p2;
어제 제가 쓴 코드는 그냥 임시로 작업해서 알려준거니까 그대로 적지말구 네이밍 한번 검토해주세용

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
> +    private(set) var NaverSearchData: NaverSearchResponse?
p2;
그리고 이 변수 지금 안쓰는거 같은데 맞을까요?

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
> +    let items: [Item]
p2;
위에 마크 주석이랑 구조체 이름이랑 안맞아요.
여기는 그냥 `NaverResponse`로 하면 되겠어요

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
> +struct Item: Codable {
p2;
여기 이름 변경..! 해주세용
여기가 `NaverSearchResponse`로가는게 맞겠네요
그리고 같은 타입인 title, image, author는 한 줄로 적어주면 더 코드가 간단해지겠네요.

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +    var searchType = 0
p3;
이 친구는 뭔가용?
서치 타입이 있는 이유는 뭔가용?
변수명만 보고 이해가 가능하도록 작성해주세요
searchType이 그냥 숫자로 0,1로 되어있으니 이해가 잘 안됩니다.
enum으로 만들어도 되겠어요

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
>      var imgaeUrl: String = ""
p3;
이거 그때 급하게 하느라 프로퍼티로 값 전달하는거로 했는데 프로토콜-딜리게이트 패턴을 써보는것도 좋겠네요

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +        NaverSearchAPI.shared.getNaverSearchData(d_titl: d_titl, d_isbn: d_isbn, display: display) { response in
p3;
지금은 네이버에서 검색api중 도서 검색밖에 사용하지 않지만 나중에는 다른 것도 쓸 수 있죠.
그래서 `getNaverSearchData`보다 `searchNaverBooks` 혹은 `getNaverSearchedBooks`같은 명명도 좋아보입니다.
간결함이름보다 명료한 이름이 알아듣기는 더 좋을것같아요~~
https://www.swift.org/documentation/api-design-guidelines/ 참고바랍니다~

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                nextVC.searchType = 1
p2;
위에 적은거랑 같은 코멘트에용.
`searchType`이 1인건 뭐고 0인건 뭐인지 여기 코드만 보고는 작성자 외에는 이해가 쉽지 않을 수 있어요.
위에 변수를 열거형으로 바꾸고 CaseIterable프로토콜 준수해서 각 case를 순회하도록 리팩할 수 있겠네요~
https://developer.apple.com/documentation/swift/caseiterable
```swift
enum SearchType: CaseIterable {
    case something
    case ...
}
```

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
> +struct Item: Codable {
question;
`Codable` 프로토콜은 어떤 것이고, 우리는 왜 채택했을까요?

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                self.bookInfoList = [BookInfoModel(image: "", title: "", author: "")]
p4;
여기도 `BookInfoModel` 모델 말고 다른 이름을 사용할 수 있다면 뭐가 좋을까요?

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                if [BookInfoModel(image: "", title: "", author: "")].isEmpty {
p3;
위에 줄에서 `self.bookInfo`로 [BookInfoModel(image: "", title: "", author: "")] 값을 넣어준 거같은데, 왜 `self.bookInfo.isEmpty`로 안하신건지 궁금해용~~

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                    nextVC.dataBind(model: BookInfoModel(image: response[0].image, title: response[0].title, author: response[0].author))
p3;
혹시 response[0]으로 하드코딩 하다 오류가 날 수 있으니 이런식으로 바꿔볼 수도 있겠네요~
```suggestion
                    let info = response[0]
                     nextVC.bookInfo = [BookInfoModel(image: info.image, title: info.title, author: info.author)]
                     nextVC.dataBind(model: BookInfoModel(image: info.image, title: info.title, author: info.author))
```

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +        getNaverSearchData(d_titl: "", d_isbn: "\(code)", display: displayCount)
p3;
여기도 전 줄에 있는 `isbnCode`를 사용하는게 맞아보이네요~~!
```suggestion
        getNaverSearchData(d_titl: "", d_isbn: "\(isbnCode)", display: displayCount)
```

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +                guard (self.bookSearchView.searchTextField.text?.isEmpty) == nil else {
p3;
뒤에 nil부분 빼고 `self.bookSearchView.searchTextField.text?.isEmpty`로는 적을 수 없는건가용??

2023-03-04 07:34 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +            for i in 0..<response.count {
p4;
`indices`를 써볼 수도 있겠네용~
https://developer.apple.com/documentation/swift/collection/indices-swift.property-9kkbf

2023-03-05 02:45 UTC, duyeong-ko commented on Peekabook/Peekabook/Network/API/NaverSearchAPI.swift
> +    private(set) var NaverSearchData: NaverSearchResponse?
맞습니닷,, 🙇‍♀️ 삭제할게요!

2023-03-05 05:30 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +    var searchType = 0
enum이 더 좋을 것 같아 enum으로 바꿨어요! 🫶

2023-03-05 05:47 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                if [BookInfoModel(image: "", title: "", author: "")].isEmpty {
앗 불필요한 코드인것 같아요! 수정했어요!

2023-03-05 05:57 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                self.bookInfoList = [BookInfoModel(image: "", title: "", author: "")]
음,,,,, 기본적인 책정보니까 BasicBookInfoModel..?

2023-03-05 06:00 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +                guard (self.bookSearchView.searchTextField.text?.isEmpty) == nil else {
Optional type 'Bool?' cannot be used as a boolean; test for '!= nil' instead 라는 에러가 떠서 == nil부분을 넣었어요,,!

2023-03-05 06:27 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                nextVC.searchType = 1
감사합니다!! ⚡️⚡️

2023-03-05 06:30 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BarcodeVC.swift
> +                self.bookInfoList = [BookInfoModel(image: "", title: "", author: "")]
기본은 뭐고 기본이 아닌 타입은 뭔가여?

2023-03-05 06:31 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +                guard (self.bookSearchView.searchTextField.text?.isEmpty) == nil else {
` self.bookSearchView.searchTextField.text!.isEmpty`로 해도 뜨나요?

2023-03-05 06:38 UTC, merged