Refactor/#163 팝업뷰 코드 리팩토링
team-peekabook/Peekabook-iOS pull request #164
Opened 2023-03-05 09:44 UTC by 6uohul

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- refactor/#163

👷 **작업한 내용**

팝업뷰 컴포넌트화

## 🚨 참고 사항

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro Max - 2023-03-05 at 18 41 25](https://user-images.githubusercontent.com/83493636/222953148-0eca6b2d-56d9-4b03-8b5b-4bd11d4bf353.gif)|

## 📟 관련 이슈
- Resolved: #163

2023-03-05 10:08 UTC, devxsby requested changes
고생했어용 👍🏻
하지만 한단계를 더 나아가서 커스텀 뷰를 만드는 방법을 익혀보면 더 좋을거같습니다~~
간단하지만 참고할만한 블로그 링크 첨부할게요! https://m.blog.naver.com/tksrl0379/222021270395
이거 참고해서 코드 다시 짜주세요!

2023-03-05 10:08 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +class CustomPopUpView: UIView {
p2;
상속 안받는 클래스는 `final` 키워드 잊지말고 붙여주는 습관을 갖도록 해봅시다
그 이유는 정리해서 우리 노션에 공유해주면 좋을거같아용~

2023-03-05 10:08 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    }
p2;
`setUI` 메서드의 역할과 책임에 대해서 다시 생각해주세용.
그리고 지금 배경색을 설정하는게 여기저기 흩어져있어요

2023-03-05 10:08 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    }
p1;
은닉화가 이루어져있지 않은데 프로퍼티를 밖에서 노출시키지말고, 메서드로 감싸주세요

2023-03-05 10:08 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +        }
p2;
저번 회의에 클로저 안에 make 로 적지 않고 $0 축약인자로 사용하기로 한거같은데 고쳐주세용~~~~

2023-03-05 10:08 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    }
p2;
지금 initializer에 아무처리도 없군용..!!!
커스텀 뷰 만들때 상황에 따라 다른 initializer 를 만든 뒤 객체 생성 시 알맞은 매개변수를 넣어서 호출해도 됩니다.
지금 같은 경우는 addTarget 하는 부분을 이렇게 생성자를 활용해서 바꿔볼 수 있겠네용.

```swift
    override init(frame: CGRect. isTouchedEnabled: Bool) {
         super.init(frame: frame)
         setUI()
         setLayout()
         self.isTouchedEnabled = isTouchedEnabled
     }
```
그리고 이 클래스 안에 addTarget 액션에 관한 메서드를 따로 정의해주면 되겠죠?

그럼 밖에서 이 클래스를 부를때 이런식으로 초기화시킬 수 있겠네요.
```swift
private let popUpView = CustomPopUpView(isTouchedEnabled: true)
```
이렇게하면 지금 캔슬버튼과 컨펌버튼 프로퍼티를 internal로 공개하지 않고 private 하게 할 수 있겠죠..

2023-03-05 11:38 UTC, devxsby commented
추가로 책 등록할때 텍스트 뷰 컴포넌트 레이아웃 깨지는거 반영해주세용 ~~ @duyeong-ko

2023-03-05 12:18 UTC, duyeong-ko approved these changes
컴포넌트화 수고하셨어용~~ 저와함께 private으로 바꿉시댜.. 💨🫶

2023-03-06 06:45 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    }
오오오! 감사합니다 !!

2023-03-09 03:59 UTC, devxsby approved these changes

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/BookDetail/VC/DeletePopUpVC.swift
> +    @objc func touchConfirmButtonDidTap() {
question;
이 메서드 두개는 왜 private이 제거된건가요??
그리고 이름에 단순 touch 모드가 touch up inside 1개인거같은데  touch와 tap이 두 개 다 들어가잇는 이유는 뭔가요?

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpVC.swift
> +        confirmPopUpview.getConfirmLabel().text = personName + I18N.BookProposal.confirm
p2;
여기 함수는 텍스트를 이렇게 넣도록 리팩해봐도 좋겠네요
```swift
confirmPopUpview.getConfirmLabel(personName, I18N.BookProposal.confirm)
```

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpVC.swift
> +    @objc func touchConfirmButtonDidTap() {
question;
여기도 마찬가지로 은닉화가 해제된 이유가 궁금해요.

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +final class CustomPopUpView: UIView {
p2;
지금도 좋지만 버튼이 2개일 때 말고 1개인 버전, 그리고 타이틀 말고 서브타이틀도 있는 버전까지 확장성있게 타입을 확장해보면 좋겠네용

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    }
p3;
여기 함수는 다르게 바꿔보면 좋겠네요

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    init(frame: CGRect, style: ButtonLabelStyle, viewController: UIViewController) {
p2;
여기 부분 이니셜라이저로 지정한 이유에 대해 설명해주실 수 있나요?

2023-03-09 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    }
p3;
코드가 중복되는 경향이 있지만 나쁘지 않아요. 잘했어용~ 👍🏻
추가로 버튼 스타일에 지금 너무 많은 역할이 들어가 있는것 같네요. 나중에 리팩해보면 좋을거같아용

2023-03-09 06:06 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +final class CustomPopUpView: UIView {
넵 나중에 다시 이슈파서 확장성있게 바꿔보겠습니당!

2023-03-09 06:07 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpVC.swift
> +    @objc func touchConfirmButtonDidTap() {
Custom View에서 VC의 함수에 접근해야해서 은닉화를 해제했습니다..! 
또 다른 방법이 있을까용..??

2023-03-09 06:07 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Proposal/VC/ConfirmPopUpVC.swift
> +        confirmPopUpview.getConfirmLabel().text = personName + I18N.BookProposal.confirm
넵..!!

2023-03-09 06:08 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/BookDetail/VC/DeletePopUpVC.swift
> +    @objc func touchConfirmButtonDidTap() {
엇.. 함수명 수정하겠습니돠

2023-03-09 06:16 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    init(frame: CGRect, style: ButtonLabelStyle, viewController: UIViewController) {
VC와 버튼 라벨의 스타일을 매개변수로 넣어서 나중에 객체 생성 시 상황에 따라 호출할 수 있도록 커스터마이징했습니다...!

2023-03-09 07:33 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    func getConfirmLabel(_ style: ButtonLabelStyle, _ personName: String = "") {
question;
파라미터를 보이게 하지 않은 이유가 궁금합니다.
외부에서 알아보기 쉽지 않을수도 있을 것 같아요.
그리고 PersonName은 버튼스타일과 관계 없이 항상 필요한 사항이 아니면 옵셔널로 처리하는게 더 좋지 않을까 생각이 되네용.

2023-03-09 07:33 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +            // confirmLabel.text = I18N.BookDelete.popUpComment
question;
여기 주석은 뭔가용?

2023-03-09 07:33 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +            // confirmLabel.text = I18N.BookDelete.popUpComment
오 홀리몰리 당장 사라져줘...

2023-03-09 07:34 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    func getConfirmLabel(_ style: ButtonLabelStyle, _ personName: String = "") {
그러네용..!! 수정하겠습니다 감사해요 🫶🏻🫶🏻

2023-03-09 07:39 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    init(frame: CGRect, style: ButtonLabelStyle, viewController: UIViewController) {
이렇게 커밋 내역도 같이 코멘트 달아주시면 확인 쉬울것 같습니다 !! [0ce9756](https://github.com/team-peekabook/Peekabook-iOS/pull/164/commits/0ce9756864fc580e2e56780d4ae7a85182fd3180)
고생하셨어용 🤎

2023-03-09 07:42 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    func getConfirmLabel(style: ButtonLabelStyle, personName: String? = "") {
question;
옵셔널인데 왜 nil이 아니라 초기화를 ""로 하셨는지 궁금해용

2023-03-09 07:42 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +            }
바인딩 야무지네요 🌟

2023-03-09 07:49 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UIComponents/CustomPopUpView.swift
> +    func getConfirmLabel(style: ButtonLabelStyle, personName: String? = "") {
그러네요..!! ""는 의미가 없군요.. 수정할게요!

2023-03-09 07:55 UTC, merged