[Refactor] #162  - 컴포넌트 은닉화 등
team-peekabook/Peekabook-iOS pull request #165
Opened 2023-03-05 12:12 UTC by duyeong-ko

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#162

👷 **작업한 내용**

- 커스텀뷰의 컴포넌트를 private으로 변경
- setUI를 setBackgroundColor로 바꿔서 역할을 명확히 함
- 커스텀뷰 레이아웃이 깨지는 오류 해결

## 🚨 참고 사항

## 📟 관련 이슈
- Resolved: #162

2023-03-05 14:05 UTC, devxsby requested changes
우선 작업하느라 너무 고생했어용..!!!!!
열심히 하는 모습 너무 보기 좋다. 👍🏻

그런데 제가 은닉화를 하라고 말하면서 리팩을 원한 방향은 이것이 아니었어용..!!
메서드를 노출시키는 방향은 맞은데 모두 이렇게 노출시키는 건 객체지향적인 코드가 아닌것같아요..
https://origogi.github.io/oop/디미터의-법칙/ 이 블로그 한 번 참고해주시고용

인영이 풀리퀘에도 적어놓았듯이 이니셜라이저를 활용해보면 더 좋은 방향이 나올 거 같습니다~~!!
https://m.blog.naver.com/tksrl0379/222021270395

2023-03-05 14:05 UTC, devxsby commented on Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
> +}
p2;
이거 위에 `NaverSearchResponse`랑 동일한것같은데 언제 사용하는 건가요?
필요없으면 하나는 지워도 될 것 같아요.

2023-03-05 14:05 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +        bookSearchView.getSearchTextField().delegate = self
p3;
지금 코드는 결합도가 굉장히 높아요.
디미터 법칙에 대해 공부해보면 좋을 것 같아요.

2023-03-05 14:05 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +
question;
이 친구는 어떤 이유로 추가된걸까용?

2023-03-06 07:12 UTC, duyeong-ko commented on Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
> +}
모든 vc나 tvc에서 책 정보(책제목, 저자, 이미지)를 저장하는 BookInfoModel을 사용했었는데,
NaverSearchResponse랑 동일하네요! 감사합니닷
여러곳에서 책정보를 나타낼때 쓰이는데 NaverSearchResponse라는 네이밍은 책정보를 나타내는 것과 조금 다른 것 같아
BookInfoModel로 전부 통일했어요 혹시 네이밍이 적절하지 않다면 말씀해주세용.. 🫶

2023-03-06 07:13 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +        bookSearchView.getSearchTextField().delegate = self
기차 충돌하지않게! 다시 작성할게요 감사합니다~~!!

2023-03-06 07:30 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +
상위 뷰에서 커스텀뷰의 크기가 바뀌면 커스텀뷰 내 boxView의 크기도 동적으로 변경시키기 위해 작성했습니다,,!

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +        static let memoPlaceholder = "메모를 남겨주세요"
p3;
여기 나중에 이름 헷갈릴거같은데 이대로 둬도 괜찮을까용?
아니면 원본만 남겨두고 호출부에서 `commentPlaceholder` + `"           "` 이런식으로 써도 괜찮을거 같아용
어떻게 생각하시나요~~?

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
>          static let memoSample = "메모는 50자 작성이 가능합니다.메모는 50자 작성이 가능합니다.메모는 50자 작성이 가능합니다."
p2;
이 샘플코드는 지워도 될거같슴다!

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Network/DTO/NaverSearch/NaverSearchResponse.swift
> +struct BookInfoModel: Codable {
이름 바꾸니 훨 좋네용 👍🏻

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +        $0.setImage(ImageLiterals.Icn.back, for: .normal)
p4;
이건 개취인데 저는 디자인 지정은 위에 적고 기타 액션 코드는 그 아래에 편입니다 ㅎㅎ
이것도 저만의 컨밴션을 지키는거라고 할까나요..? 허허.

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    }
p3;
메서드 이름이 모호한것같습니다..

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    }
p3;
이 커스텀 텍스트 뷰라는 파일에서 공통되는 부분은 따로 빼서 일괄 적용해도 좋을 것 같아요.
예를들어 `boxView.backgroundColor = .clear` 이런거요~!
`setBackgroundColor` 메서드 에서 해줄수 있겠네요~
바뀌는 부분만 새로 지정하면 될 것 같습니다.
추가로 나중에는 좀 더 확장성있는 코드로 리팩해봐도 좋을거같아요!! (지금도 잘했다.)

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    }
question;
이 친구들은 뭔가용?

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +        }
p2;
이친구는 따로 빼주세요~

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
>      override init(frame: CGRect) {
p2;
이니셜 라이저를 활용해보면 좋을거같아요!!
https://github.com/team-peekabook/Peekabook-iOS/pull/164 이거 인영이가 작업한건데 한 번 참고해봐도 좋을듯!

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
>      @objc func searchBtnTapped() {
question;
여기는 `internal` 인 이유가 있을까요~~?

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
> +        userSearchView.getSearchTextField().delegate = self
p3;
여기는 메서드로 안 만들어도 될거같아요

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTVC.swift
> +        }
p2;
`I18N`에 넣어주세용~~~

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTVC.swift
> +        self.bookShelfType = bookShelfType
야무지게 잘 하셨네요 🌟

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
> +            peekaCommentView.getMaxLabel().text = "\(descriptions.count)/200"
p4;
이 부분은 메서드로 안가져와도 될거같아여.. 몬가 더 이상해진 느낌인데 두영님 생각 궁금해요...

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
> +    }
p4;
꼭 굳이 모든걸 별개의 메서드로 만들라는 의미는 아니였습니다..1!!!!?!!!!!!!!

2023-03-09 14:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomSearchView.swift
> +    }
p2;
이쪽 코드 쓰이고 있는거 맞나요??
아닌거같은데 확인 부탁드려용.
지금 메서드가 너무 많아져서 오히려 더 헷갈리는것같아요오오...

2023-03-09 14:20 UTC, duyeong-ko commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +        static let memoPlaceholder = "메모를 남겨주세요"
😵 너무좋은것같아요!! 진짜,, 지니어스
수정할게용!

2023-03-10 07:01 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    }
updateAddBookMemoView, updateBookDetailMemoTextView 이렇게 메서드 이름 바꿔보았습니다 더 좋은 이름이 있다면 말씀해주세용 ㅎㅎ

2023-03-10 07:02 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    }
외부에서 textview와 maxlabel에게 접근하기위한 메소드입니다. 하지만 좋지 않은 코드인 것 같아서 수정하려고해요!

2023-03-10 07:08 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserSearch/VC/UserSearchVC.swift
>      @objc func searchBtnTapped() {
앗 아니용 수정했어요~!

2023-03-10 07:11 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/BookDetail/VC/EditBookVC.swift
> +            peekaCommentView.getMaxLabel().text = "\(descriptions.count)/200"
맞아요... 수정하겠습니다~!

2023-03-10 07:12 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CustomSearchView.swift
> +    }
그렇네요! 삭제했습니닷~~

2023-03-10 07:36 UTC, devxsby approved these changes

2023-03-10 07:36 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +        static let friendLabel = "친구에게 책 추천하기"
p2;
꼭 라벨에 쓰이라는 법은 없는 것 같아요.
그냥 `addMyBookshelf`, `recommendFriendBookShelf` 같이 직관적으로 바꿔도 좋을것같습니다~~

2023-03-10 07:36 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +            $0.top.bottom.equalToSuperview()
p2;
한 줄로 합쳐주세용~

2023-03-10 07:36 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +        if (textView.text == I18N.BookDetail.commentPlaceholder + "           ") ||
p3;
위에 프로퍼티로 만들어주세용 (하드코딩 x)
```swift
private let placeholderBlank: String = "          "
```

```suggestion
        if (textView.text == I18N.BookDetail.commentPlaceholder + placeholderBlank) ||
```

2023-03-10 07:36 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    func updateBookDetailMemoTextView() {
p3;
set → update로 일괄변경된거 말고 차이점이 없네요.. 🥲
제가 코멘트 남긴건 뭘 업데이트하는지, 뭘 세팅하는지가 안적혀있어서 모호함 + 공통되는 코드는 다른 메서드로 뺄 것을 제안한 거였습니다~!

예시로 두번째 메서드는 지금 배경색만 지정하고있는데 `updateEditBookCommentTextView` 라는게 뭘 업데이트 한다는 건지 잘 이해가 안되서였어요.
그리고 해당 코드는 다른 메서드에서도 중복되니까 그냥 `setBackgroundColor`로 옮기면 어떨가 싶어서 남긴 코멘트였습니다~!
지금 메서드를 일부러 분리하다보니 역할도 구분이 안되어있는 것 같고 그래서 네이밍도 모호한 것 같네요..!!
이 쪽은 여기서 끝내고 다음에 다시 작업해보면 좋을 것 같아요~~

2023-03-10 07:37 UTC, duyeong-ko commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +        static let friendLabel = "친구에게 책 추천하기"
오옹.. 훨씬 직관적이군여 📝 수정할게요!

2023-03-10 07:41 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +        if (textView.text == I18N.BookDetail.commentPlaceholder + "           ") ||
배워갑니닷!!! 👍🏻

2023-03-10 07:55 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    func updateBookDetailMemoTextView() {
textView의 배경색은
EditBook의 CommentTextView를
boxView.backgroundColor = .clear
해주던지,

AddBook의 CommentTextView를
boxView.backgroundColor = .peekaWhite_60
로 해주던지

이렇게 하나는 설정을 해줘야해서 빼지 못하고 두었습니다 🥲 하지만 둔다고 해도 이 메서드 이름은 모호한 것 같네용..!

코드 다시 보니 backgroundColor가 clear인 경우가 더 많아서 초기 색상을 clear로 바꾸고 몇개만 beige컬러로 바꾸도록 코드를 줄이고, 한줄짜리 메서드는 이름도 바꿔주었습니다!

2023-03-10 07:58 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UIComponents/CustomTextView.swift
> +    func updateBookDetailMemoTextView() {
이런 경우는 전달인자로 받아와서 설정해도 되겠네요~~!
아무튼 잘 ! 했! 어 ! 요 !!  두영 !! 공 !! 쥬 💐
이제 컨플릭트 해결하고 머지 해도될것같슴당~~ 고생하셨어용 ㅎㅎㅎ

2023-03-10 08:24 UTC, 6uohul approved these changes
깔끔하게 잘 짜신 것 같아요~!!
너무너무 고생하셨슴돵 🫶🏻👍🏻

2023-03-10 08:24 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +            $0.leading.trailing.equalToSuperview().offset(20)
위에 centerX 코드는 없어도 될 것 같아용!!

2023-03-10 08:24 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +        let description = (peekaCommentView.getTextView().text == I18N.BookDetail.commentPlaceholder) ? "" : peekaCommentView.getTextView().text
👍🏻쫭

2023-03-10 08:24 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +
여기 개행은 컨벤션인가용?? (몰라서 여쭤봄니다..)

2023-03-10 08:24 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +
주석 발견 !!

2023-03-10 08:24 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTVC.swift
> +        self.bookShelfType = bookShelfType
두두 멋져~!!

2023-03-10 08:24 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/AddBook/Views/BookInfoTVC.swift
> +        }
역시 멋지시네요..!!

2023-03-10 08:35 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/AddBookVC.swift
> +            $0.leading.trailing.equalToSuperview().offset(20)
centerX를 없애면 leading trailing이 있어도 코드가 깨져용.. 🥲

2023-03-10 08:36 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +
넹 저는 self와 /  다른 요소 이렇게 구분지어서 사용하고있어욥!

2023-03-10 08:37 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/AddBook/VC/BookSearchVC.swift
> +
어머!! 컨플릭트를 해결하면 주석이 생기는구나.. 찾아주셔서 감사해용~!!

2023-03-10 08:38 UTC, merged