[Refactor] #152 - 추천탭 뷰 리팩토링
team-peekabook/Peekabook-iOS pull request #168
Opened 2023-03-09 09:29 UTC by 6uohul

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- chore/#152

👷 **작업한 내용**

- 책 제목, 저자 레이아웃 수정
- 추천사 레이아웃 수정

## 🚨 참고 사항

책 제목과 저자가 둘 다 길어진 경우 임의로 저자는 전체 너비의 30%를 차지하도록 설정했어요

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 14 Pro Max - 2023-03-09 at 18 28 02](https://user-images.githubusercontent.com/83493636/223978984-cc573f3b-5bbf-4a2c-ac8f-3d6b0debbb81.gif)|

## 📟 관련 이슈
- Resolved: #152

2023-03-09 13:30 UTC, duyeong-ko reviewed
인영씨 수고하셨어요~~ ✊🏻🍀

2023-03-09 13:30 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>              )
오 이거 이렇게 바꾼거였군요! 👍🏻

2023-03-09 13:30 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +    }
우선순위를 이렇게 설정하셨군요~! 오옹 알아갑니다..

2023-03-09 13:38 UTC, devxsby requested changes
고생하셨습니다~~
대부분 잘 적용된거같아요 😇
코멘트 남긴 부분만 확인 부탁드려요!

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +
p3;
갑자기 개행은 왜하게 된건가용? 컨밴션이 바뀌게 되신건가요??

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>      private func setSubviews() {
p3;
이 함수는 그냥 `addSubviews`라는 동일 이름으로 가져가도 될거같아요.
이유는 서브 뷰들을 세팅하는 과정이 전혀 없고 추가하는 역할만 들어가있기 때문입니다.
인영님의 생각은 어떠하신가용~?

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +                direction: .reverse,
👍🏻

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>          if indexPath.item == 0 {
p2;
여기도 그냥 `indexPath.item`로 접근하는 것보다 타입을 만드면 더 보기 좋겠네요.
아니면 위에 만들어놓은 `recommendTypes`으로도 쓸 수 있겠네요

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>  extension RecommendVC: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
question;
`UICollectionViewDelegate`는 어떤 역할을 하고, `UICollectionViewDataSource`는 어떤 역할을 하는 프로토콜인지 설명해주실 수 있나요? `UICollectionViewDelegateFlowLayout`는 왜 채택하신건지도 궁금해요.

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
> +        tableView.snp.makeConstraints {
p3;
여기 `tableView`는 어디에 있는 테이블뷰인가요? 어떤 역할인지 잘 모르겠어요
이름만 보고는 해당 뷰페이저가 있는 뷰의 구조를 잘 캐치하기 어려운 면이 있는것같아요..!!

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +final class RecommendListTVC: UITableViewCell {
question;
파일명이 바뀌었는데 어떤 이유로 바뀌셨는지 궁금해요.
그리고 파일명이 바뀌었으면 위에 2번째 파일설명하는 주석부분도 일괄적으로 같이 바꿔주셔야 해요.

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +        setPriority()
p4;
모든 메서드가 `set`으로 시작하고 있군요..!!
setting 한다는 의미에서 작성하신 것도 좋지만 다른 이름도 많으니 API Design Guide 잘 읽어보시면 좋겠습니다~

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +            $0.leading.equalTo(bookNameLabel.snp.trailing).offset(7)
p4;
저는 레이아웃을 지정하는데에 통일성을 갖추는 편이에요.
보통 top, leading, trailing, width, height 순서로 위치 → 크기를 잡는편입니다.
사소하지만 이것도 본인만의 컨밴션이라고 생각하고, 지켜야 한다고 봅니다~~!
그런 의미에서 여기 부분도 인영님 코드의 컨밴션을 지켜주면 좋을 것 같아요~!

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +            $0.width.lessThanOrEqualToSuperview().multipliedBy(0.3).constraint.isActive = true
조씁니다 🦈

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +            $0.width.equalTo(122)
question;
이 친구는 위치가 안잡혀있고 크기만 지정되어있는데, 현재 오토레이아웃 에러가 안나나요?

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +    }
Hugging Priority, Compression Priority 사용 좋네요 👍🏻

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTypeCVC.swift
>      override var isSelected: Bool {
question;
이건 왜 `override` 하신건가용?

2023-03-09 13:38 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +final class RecommendListTVC: UITableViewCell {
나머지 파일들도 싹 검토해주세요~~

2023-03-09 13:44 UTC, duyeong-ko approved these changes

2023-03-10 02:32 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
> +
팝업VC와 컨벤션을 통일하려고 했는데 제가 착각했던 것 같아용
다시 수정하겠습니당
꼼꼼히 확인해주셔서 감사해욥🥹

2023-03-10 02:33 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>      private func setSubviews() {
그러네용~~!!

2023-03-10 02:34 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +    }
나중에 Hugging과 CompressionResistance에 대한 아티클도 올리겠습니당~~~!!

2023-03-10 02:40 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>          if indexPath.item == 0 {
오오.. 시도해보겠습니당!!

2023-03-10 03:52 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +            $0.width.equalTo(122)
StackView 내부에 BookContainerView와 bookCommentsContainerView를 넣어서 width만 고정시켜주었습니다!

2023-03-10 04:00 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendTypeCVC.swift
>      override var isSelected: Bool {
다른 뷰로 전환했다가 돌아왔을 때 이전에 선택한 상태를 유지하고싶어서 재정의했습니다!

2023-03-10 04:01 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>  extension RecommendVC: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
이 부분은 더 공부해봐야겠네용..

2023-03-10 04:04 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendedVC.swift
> +        tableView.snp.makeConstraints {
recommendedVC와 recommendingVC에 tableView는 각각 하나씩만 들어가서 이름을 간단히 지었었어요
더 구분할 수 있도록 이름 수정하겠습니다!

2023-03-10 04:08 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +final class RecommendListTVC: UITableViewCell {
예전에 파일명은 recommendTVC와 recommendCVC이었습니다!
TVC와 CVC가 어떻게 역할이 다른지 구분하기 어려울 것 같아서 
TVC는 책 리스트를 나타내고, CVC는 종류(추천받은 책/추천한 책)를 나타낸다고 이름을 수정했습니다.

2023-03-10 04:23 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/Views/RecommendListTVC.swift
> +final class RecommendListTVC: UITableViewCell {
넵!! 👍🏻
주석 부분도 같이 수정해주세용~!

2023-03-10 04:24 UTC, devxsby commented on Peekabook/Peekabook/Presentation/Recommend/VC/RecommendVC.swift
>  extension RecommendVC: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
테이블뷰, 컬렉션 뷰가 재사용되고 그러져는 플로우에 대해서도 공부해보면 좋을듯!!

2023-03-10 04:29 UTC, devxsby approved these changes

2023-03-10 09:14 UTC, merged