[Feat] #186 - 케밥버튼, 신고하기 뷰 레이아웃
team-peekabook/Peekabook-iOS pull request #188
Opened 2023-03-24 02:56 UTC by duyeong-ko

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#186

👷 **작업한 내용**

- 케밥버튼과 신고하기 뷰 레이아웃

## 🚨 참고 사항

- declareVC에서 TVC의 label에 접근해야하기때문에 label을 public으로 지정했습니다.
- tvc의 위아래 둘 다 선이 있어야해서 tvc에서 underLineView를 만들고, vc에서 tvc의 top에 따로 topLine을 추가하는 방식으로 구현했는데, 어제는 라인이 잘 떴는데 오늘은 왜인지 topLine이 나타나질않네요,, 추후 수정하겠습니다! (참고로 시뮬레이션영상은 tvc 아래 선이 없는 버전에서 녹화한것입니다.. 😅 이것만 다르고 전부 동일해요!)

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/101977975/227411911-4d2d4d35-ddd0-40cb-9c0e-4caa4ceb946a.mov" width ="250">|

## 📟 관련 이슈
- Resolved: #186

2023-03-24 14:35 UTC, devxsby requested changes
> declareVC에서 TVC의 label에 접근해야하기때문에 label을 public으로 지정했습니다.

리팩해봐도 좋을거같아요~ 그리구 신고 메뉴 여러개인거 array말고 enum으로 만들어도 좋을 듯 !

> tvc의 위아래 둘 다 선이 있어야해서 tvc에서 underLineView를 만들고, vc에서 tvc의 top에 따로 topLine을 추가하는 방식으로 구현했는데, 어제는 라인이 잘 떴는데 오늘은 왜인지 topLine이 나타나질않네요,, 추후 수정하겠습니다! (참고로 시뮬레이션영상은 tvc 아래 선이 없는 버전에서 녹화한것입니다.. 😅 이것만 다르고 전부 동일해요!)

여기 부분은 수정해주시고 다시 코멘트 남겨주세용~~!!!
고생하셨습니당. 두두공쥬. 진짜. 잘하넹? 멋찐 오비선배다.🤎

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
> +        static let more = UIImage(named: "icn_more")?.withRenderingMode(.alwaysOriginal)
p3;
more 아이콘만 코드로 `withRenderingMode`를 지정하신 이유가 있으실까요~~?
에셋 인스펙터에서 지정해주셔도 될듯합니다~~ 
<img width="254" alt="스크린샷 2023-03-24 22 51 24" src="https://user-images.githubusercontent.com/80062632/227539401-22b0c9be-1313-448a-999e-081e58baf4c7.png">

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
> +        static let uncheckedButton = UIImage(named: "icn_radio_button_unchecked")
p2;
지금 이미 `check`  이름을 가진 아이콘이 있습니다..!!!

단순히 check, uncheck로 지정하면 나중에 에셋이 헷갈릴 것 같으니 원래 피그마 에셋 이름대로인 radio_check 나 모양을 기반으로 한 circle_check나 뷰이름_check등으로 부르는게 더 좋아보입니다~!

추가로 현재 이미지를 보니 check 표시가 아닌 둥근 표시이니 check라는 네이밍보다 filled unfilled(위에 아이콘 네이밍 참고)등으로 불러볼 수도 있겠네요..! 🙂

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +    }
p2;
신고하기 뷰 이름이 `Declare`인것 보다 차라리 `Report`라는 것으로 바꾸는게 좋아보여요.
네이밍에 관한 부분은 검색도 많이 해보고, 저 같은 경우는 이름짓기 어려운거는 비슷한 기능이 있는 앱을 키고 + 핸드폰 영어 언어로 바꿔서 확인해보는 방식을 씁니다!! 지금 인스타는 신고하기 기능을 `Report`로 사용하고 있네요~!

![IMG_9481](https://user-images.githubusercontent.com/80062632/227541946-5cf5540c-dbe0-4d91-ae5a-56bf818eca5d.jpg)
![IMG_9480](https://user-images.githubusercontent.com/80062632/227541956-42796d0a-e294-41c6-b6b9-df3fd43a8a13.jpg)

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +        static let declareInfo = "신고하신 내용은 검토 후 빠른 시일 내 조치하겠습니다."
p2;
지금은 reason1, 2, ... 5 등을 뷰를 보고 직접 순서대로 부여해서 간단히 네이밍할 수 있지만, 웬만해서는 한글 뜻 그대로를 영어로 옮겨서 네이밍해주시는 게 좋습니다!
나중에 reason1이 뭐였는지 기억이 안날수도 있고, 순서가 바뀔 수도 있고, 새로운게 추가될 수도 있고 다양한 경우의 수가 있을 수 있으니까요~~!
번거로우시겠지만 이 부분 네이밍 다시 검토 부탁드릴게요 🙏🏻

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
> +        lb.lineBreakMode = .byCharWrapping
👍🏻

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
> +        actionSheet.addAction(UIAlertAction(title: "취소", style: .cancel, handler: nil))
p2;
여기 타이틀 부분은 왜 하드코딩 되었을까용?? `StringLiterals`에 등록 부탁드립니다~!

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +final class DeclareVC: UIViewController {
p1;
신고하기 뷰 네이빙 변경 부탁드릴게요!

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +        $0.dataSource = self
p3;
`setDelegate`로 넘겨도 되겠네요~~

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +    }
p3;
이 함수는 위에 따로 빼서 `declareTableView` 에서 delegate하는 코드도 옮겨서 공통으로 쓰는게 좋겠네용

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +    }
bye

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +        cell.label.text = declareArray[safe: indexPath.row]!
`safe`까지 야무지게 잘 쓰셨네요 굳~! ♥️
그런데 cell의 label 프로퍼티를 직접적으로 노출하지 않기 위해선 어떻게 리팩할 수 있을까요~~?
메서드를 잘 활용해보세용!

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +final class DeclareTableViewCell: UITableViewCell {
p2;
다른 파일은 약어로 TVC로 적고 있으니 여기도 변경해주세용~

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +        register()
p4;
`registerCell`도 괜찮을듯!??

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +    }
p4;
`containerScorllView` 로 해두는게 좋겠어요~!
나중에 뷰 올릴때 뷰 자체를 올리고 내릴지, 스크롤의 위치를 바꿀지 컨테이너뷰라는 이름만 보면 잘 모르겠쬬?

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +    ]
p1;
여기는 위에 코멘트 확인해주시고 수정 부탁드릴게요~!
그리고 array로 만드신 이유가 있으실까요? 다른 타입으로 만들어볼수도 있겠네용
enum 타입으로 지정하고 원시값으로 지정해주는 방식도 좋아보입니다~~!
```swift
enum ReportMenu: String {
    case reason1 = I18N.Declare.reason1
    case reason2 = I18N.Declare.reason2
    ...
}
```

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +        $0.returnKeyType = .done
여기 텍스트뷰는 커스텀 텍스트뷰를 안쓰네요..!!
`isFirstResponder` 지정되어 있나용~~?

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        $0.addTarget(self, action: #selector(radioButtonDidtap(_:)), for: .touchUpInside)
p3;
상태에 따라 이미지 바꿔서 지정하는거 아주 조씁니당 🦈
요기 버튼은 왜 타입이 `.system`으로 지정이 안 되어 있을까용?
그리고 22 line도 `action: #selector(radioButtonDidtap)`으로만 적어도 될거같아요~

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +    var radioButtonAction: (() -> Void)?
p3;
위치가 제법 뜬금포. 입니다.
그리고 이 클로저는 뭐하는 친구인가요??

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +    let label = UILabel().then {
p3;
리팩 고! 그리고 기왕 적는거 `titleLabel`이라고 명시해주세용~~

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        backgroundColor = .peekaBeige
p2;
이 친구들은 layout 지정하는 코드가 아닌뎁쇼,,??

2023-03-24 14:35 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        tableView.delegate?.tableView?(tableView, didSelectRowAt: indexPath)
코드가 잘 이해가 안되는데 플로우 설명 부탁드려요~

2023-03-26 13:56 UTC, duyeong-ko commented on Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
> +        static let more = UIImage(named: "icn_more")?.withRenderingMode(.alwaysOriginal)
오 알겠습니다!! 수정할게요 ㅎㅎ 💨

2023-03-26 13:59 UTC, duyeong-ko commented on Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
> +        static let uncheckedButton = UIImage(named: "icn_radio_button_unchecked")
radio_check 로 가겠습니다 ㅎㅎ

2023-03-26 14:02 UTC, duyeong-ko commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +    }
오 특히 뷰이름 네이밍은,, 검색을 해보고 써야겠어요,, 👍🏻 수정할게요 감사합니다!!

2023-03-26 14:02 UTC, duyeong-ko commented on Peekabook/Peekabook/Global/Literals/StringLiterals.swift
> +        static let declareInfo = "신고하신 내용은 검토 후 빠른 시일 내 조치하겠습니다."
알겠습니닿 🫶🫶!!!

2023-03-26 14:08 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/BookShelf/VC/BookShelfVC.swift
> +        actionSheet.addAction(UIAlertAction(title: "취소", style: .cancel, handler: nil))
아이고 빠트렸네요~!!! 등록할게요!!

2023-03-26 15:40 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +    ]
네엡 수정하였습니다!!! 🥰

2023-03-27 08:39 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +        $0.returnKeyType = .done
네에 여기 텍스트뷰는 비슷한부분보다 아닌 부분이 대부분이어서 커스텀뷰 사용해도 더 번거로울것같아 따로 만들었습니다!
isFirstResponder 지정할게요!! ㅎㅎ

2023-03-27 08:44 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/DeclareVC.swift
> +        $0.returnKeyType = .done
앗 여기는 텍스트뷰가 하나라 isFirstResponder 사용하지않아도 작동돼서 따로 추가하지않을게용!

2023-03-27 08:45 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        $0.addTarget(self, action: #selector(radioButtonDidtap(_:)), for: .touchUpInside)
수정할게요!! 👍🏻

2023-03-27 09:00 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        $0.addTarget(self, action: #selector(radioButtonDidtap(_:)), for: .touchUpInside)
아아 .system으로 수정하니 셀 버튼을 누르면 파란색배경이 뜨네요..?

2023-03-27 09:02 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +    var radioButtonAction: (() -> Void)?
어머낫. 얘는 사용되고잇지않군여. ㅎㅎ
지금 코드에 필요없을것같아 삭제했습니다!

2023-03-27 09:03 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        backgroundColor = .peekaBeige
setBackgroundcolor에 뺐습니다! 감사해요1!

2023-03-27 09:06 UTC, duyeong-ko commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        tableView.delegate?.tableView?(tableView, didSelectRowAt: indexPath)
테이블뷰에서 셀이 선택됐을때 visibleCells를 이용해서 모든 셀을 순회하며 
지금 셀 제외한 나머지 버튼의 셀렉티드상태를 false로 만들고
현재 버튼을 selected = true로 만들어주고 마지막에 didSelectRowAt 호출해서 선택된 셀 번호 알려주는 코드입니닷!!

2023-03-28 03:07 UTC, devxsby approved these changes
![image](https://user-images.githubusercontent.com/80062632/228117473-9e407df0-3fef-4b91-8ff7-5efa2f552dac.png)

2023-03-28 03:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/ReportVC.swift
> +}
멋찌다 고두영곤듀. 🌟🚀

2023-03-28 03:07 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/ReportVC.swift
> +    private let reportArray: [ReportMenu] = [.post, .insults, .promote, .nickname, .etc]
👍🏻

2023-03-28 03:08 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/Views/DeclareTableViewCell.swift
> +        $0.addTarget(self, action: #selector(radioButtonDidtap(_:)), for: .touchUpInside)
어랏?

2023-03-29 07:59 UTC, 6uohul commented on Peekabook/Peekabook/Global/Literals/ImageLiterals.swift
> +        static let more = UIImage(named: "icn_more")?.withRenderingMode(.alwaysOriginal)
오우.. 저도 바꾸겠습니다.. 하핫!

2023-03-30 03:40 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/ReportVC.swift
> +}
오옹 rawValue 값은 어떤 역할을 하나용?!??!

2023-03-30 03:43 UTC, 6uohul approved these changes
두두씨 왤케 잘해요. 너무 고생하셨어용

2023-03-30 03:43 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/ReportVC.swift
> +    private let reportArray: [ReportMenu] = [.post, .insults, .promote, .nickname, .etc]
두두쫭

2023-03-30 03:59 UTC, devxsby commented on Peekabook/Peekabook/Presentation/UserDeclare/VC/ReportVC.swift
> +}
@6uohul 숙제~ 
공부해서 노션에 정리하기 ~~ 😸

2023-03-30 04:25 UTC, merged