[Feat] #30 - 알림 뷰 레이아웃 구현
team-peekabook/Peekabook-iOS pull request #40
Opened 2023-01-07 14:57 UTC by 6uohul

## 🔥 *Pull requests*

⛳️ **작업한 브랜치**
- feature/#30

👷 **작업한 내용**

알림 뷰 레이아웃 구현

## 🚨 참고 사항

## 📸 스크린샷
|기능|스크린샷|
|:--:|:--:|
|GIF|![Simulator Screen Recording - iPhone 13 Pro - 2023-01-07 at 23 56 17](https://user-images.githubusercontent.com/83493636/211156837-99f0bdb6-0816-4949-b3de-46c1405f4df7.gif)|

## 📟 관련 이슈
- Resolved: #30

2023-01-07 15:20 UTC, devxsby requested changes
고생하셨어요!!
리뷰 읽어주시고 반영해서 다시 확인하고 머지할게용~~
그리고 셀 높이 동적으로 하는것까지 !!!
제가 하나에 달아놨지만 겹쳐서 다시 언급안 한 것들도 있으니 전체적으로 사악 검토부탁드려용 🤍

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/NotificationModel.swift
> +    let date: String // 나중에 date로 바꿀 예정
p2.
이거 서버에서 스트링으로 받아서 그냥 냅두고 처리하는건 함수 만들어서 따로하면 될 거 같아용~~

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    ]
p2.
더미 데이터 한 10개정도 넣고 3개는 클라에서 최신처리(빨강)하고, 나머지는 읽음처리(회색) 하는 거까지 반영해서 머지할게요!!

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.text = "알림"
p2.
I18N에 넣어주세용~~!

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.backgroundColor = UIColor.peekaBeige
p3.
요기 `.peekaBeige` 만 써도 되지않나여?? 다른 코드랑 통일성 맞추면 좋을거같아요~~~

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.showsVerticalScrollIndicator = true
question.
이걸 보여주는 것이 정녕 맞습니가?

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.isScrollEnabled = true
p3.
기본값 속성은 안넣어줘두 되지 않습니가?

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.allowsSelection = false
question.
이친구는 몬가요?

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.allowsMultipleSelection = false
question.
이친구는 몬가요?2

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        notificationTableView.rowHeight = UITableView.automaticDimension
p1.
생명주기에는 생코드 적지 않기로 해요..~ 함수로 묶든지 테이블 뷰 코드에 넣어주면 좋겟어요

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    private func register() {
p2.
어떤걸 register한다는 건지 잘 모르겠어요. 그런 의미에서 테이블 뷰 셀만 등록하는거면 `registerCells`이라는 명명이 더 좋아보여요

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        notificationTableView.backgroundColor = UIColor.peekaBeige
p2.
여기도 uicolor 지정 관련해서 통일성을 지켜주세욥!

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        }
p1.
피그마에 올라온 버튼 이미지, 위치랑 달라요. 확인 부탁드려용

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.font = .systemFont(ofSize: 18, weight: .bold)
p1.
custom font로 반영해주세요

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    private let notificationLabel = UILabel().then {
p1.
라벨 색상이 지정 안되어있어요~~ peekaRed로 넣어주삼!

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +            make.bottom.equalToSuperview()
p2.
```suggestion
            make.bottom.equalTo(view.safeAreaLayoutGuide)
```

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        return 3
p2.
더미 모델을 만들어 놨으니 상수로 지정하기 보다는 모델의 개수를 카운트 하는 것이 좋아보입니당

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +class MyNotificationTVC: UITableViewCell {
p1.
```suggestion
class MyNotificationTVC: UITableViewCell {
```

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +
p2.
Mark 주석들 영역 구분시켜서 넣어주세요~

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +    }
p2.
다른 파일과 마찬가지로 컴포넌트 하나 선언할때마다 줄 바꿈을 하는 컨밴션을 지켜주세요

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +        contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 0, left: 0, bottom: 8, right: 0))
question.
여기 엣지 넣는 코드는 뷰컨에 안넣고 셀파일에 넣어놓으신 특별한 이유가 있을까여?

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +        notiContainerView.addSubviews()
p1.
이 코드는 65 line과 중복코드인 거 같아요 삭제해주세영

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +        contentStackView.addArrangedSubviews(contentLabel, bookNameLabel)
스택뷰 사용 좋으네요. 👍🏻

2023-01-07 15:20 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    ]
p2.
그리고 지금 더미가 다양한 케이스(우리의 알람 타입 3개)가 아닌 거 같은데 다음에 서버 연결 편하게 하시려면 더미모델 좀 다양하게 넣어주시고, notiLabel로 받지말고 user로 받아서 밑에 bookName처럼 뷰컨에서 문자열 보간법으로 넣어주세요~~!

2023-01-07 15:21 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.showsVerticalScrollIndicator = true
..아니요....

2023-01-07 16:13 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/NotificationModel.swift
> +    let date: String // 나중에 date로 바꿀 예정
넵!

2023-01-07 16:13 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    ]
네 model 바로 수정하겠습니당

2023-01-07 18:30 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.isScrollEnabled = true
...맞습니다

2023-01-07 18:30 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.allowsSelection = false
당장 사라졋.

2023-01-07 18:37 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.allowsMultipleSelection = false
사라지세욧.

2023-01-07 18:38 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        notificationTableView.rowHeight = UITableView.automaticDimension
으업 당장 삭제하겠습니다

2023-01-07 18:38 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    private func register() {
오옹 수정할게요!

2023-01-07 18:43 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        }
바로 수정했습니다!!

2023-01-07 18:43 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +        $0.font = .systemFont(ofSize: 18, weight: .bold)
수정 완료했습니다!

2023-01-07 18:44 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +    private let notificationLabel = UILabel().then {
수정완료입니돠!!

2023-01-07 18:44 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/VC/MyNotificationVC.swift
> +            make.bottom.equalToSuperview()
바로 수정했씁니다!!

2023-01-07 18:45 UTC, 6uohul commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +class MyNotificationTVC: UITableViewCell {
엇 이게 무슨 의미일까용...??

2023-01-08 02:51 UTC, devxsby approved these changes

2023-01-08 04:25 UTC, duyeong-ko approved these changes
인영씨. . . 코드가 너무 깔끔한데욥,, ⭐️ 고생하셨어요~~!!

2023-01-08 04:54 UTC, devxsby commented on Peekabook/Peekabook/Presentation/MyNotification/Views/MyNotificationTVC.swift
> +        notiContainerView.addSubviews()
여기

2023-01-08 05:34 UTC, merged